---
- name: CVE-2018-0467
  hosts: labrouters
  connection: network_cli
  gather_facts: no

  #  This playbook is for example purposes only.   
  #  CVE-2018-0467 Cisco IOS and IOS XE Software IPv6 Hop-by-Hop Options Denial of Service Vulnerability
  #  https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20180926-ipv6hbh
  #  This vulnerability affects devices that are running a vulnerable version of Cisco IOS or IOS XE Software and are configured with an IPv6 address.
  #  Cisco does not provide a workaround for this vuln.  If ipv6 is not needed, it can be disabled.
  
  vars:
    interface_name: gi0/0

  tasks:
     
     - name: REMOVE IPv6
       ios_config:
          lines:  
            - no ipv6 address
          parents: interface {{ interface_name }}
