---
- name: CVE-2019-1737
  hosts: labrouters
  connection: network_cli
  gather_facts: no

  #  This playbook is for example purposes only.   
  #  CVE-2019-1737 Cisco IOS and IOS XE Software IP Service Level Agreement Denial of Service Vulnerability
  #  https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20190327-ipsla-dos
  #  This vulnerability affects routers that are running vulnerable releases of Cisco IOS and IOS XE Software and have been configured for IP SLA Responder operations.
  #  Cisco does not list a workaround for this vuln.  If ip sla responder is not needed, it can be disabled.


  tasks:
    
    - name: GET IP SLA RESPONDER COMMANDS FROM ROUTER
      ios_command:
        commands: show runn | include ip sla responder
      register: responder_output

    - name: REMOVE IP SLA RESPONDER
      ios_config:
          lines: NO {{ item }}
      with_items: "{{ responder_output.stdout_lines[0] }}"
   
      
          