---
- name: CVE-2018-0151
  hosts: labrouters 
  connection: network_cli
  gather_facts: no

  #  This playbook is for example purposes only.   
  #  CVE-2018-151 Cisco IOS and IOS XE Software Quality of Service Remote Code Execution Vulnerability
  #  https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20180328-qos
  #  This vulnerability affects devices that are running a vulnerable version of Cisco IOS or IOS XE Software and are configured with an IPv6 address.
  #  Cisco does not provide a workaround for this vuln.  If ipv6 is not needed, it can be disabled

  vars: 
    acl_number: 199

  tasks:
     
     - name:  ADD ACCESS LIST
       ios_config:
         lines:
           - access-list {{ acl_number }} deny ip any any fragments
           - access-list {{ acl_number }} permit udp any any eq 18999

     - name:  class-map match-all undesirable-udp
       ios_config:
         lines:  
           - match access-group {{ acl_number }}
         parents: class-map match-all undesirable-udp
    
     - name: policy-map drop-udp
       ios_config:
         lines: 
           - drop
         parents:
         - policy-map drop-udp
         - class undesirable-udp

     - name: control-plane
       ios_config:
         lines:
           - service-policy input drop-udp
         parents: control-plane
