---
- name: CVE-2018-0475
  hosts: labswitches
  connection: network_cli
  gather_facts: no

  #  This playbook is for example purposes only.   
  #  CVE-2018-0475 Cisco IOS and IOS XE Software Cluster Management Protocol Denial of Service Vulnerability
  #  https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20180926-cmp
  #  This vulnerability affects that are running a vulnerable release of Cisco IOS Software or Cisco IOS XE Software 
  #     with the cluster feature enabled that have not been a cluster member since the last reload
  #  Manually configuring an arbitrary cluster command switch MAC address using the cluster commander-address mac_address 
  #     command in global configuration mode prevents exploitation of this vulnerability.


   tasks:
    
    - name: GET IP SLA RESPONDER COMMANDS FROM ROUTER
      ios_config:
        lines:  cluster commander-address {{ 0c:9d:0e | random_mac }}

        